// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Rf1ZosVHly_yMdkZpSdrCr6gx4S5pGw',
    appId: '1:620058340943:web:f45b6613305cd970a1843a',
    messagingSenderId: '620058340943',
    projectId: 'weather-1650a',
    authDomain: 'weather-1650a.firebaseapp.com',
    storageBucket: 'weather-1650a.firebasestorage.app',
    measurementId: 'G-347GP28DRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wAWprdVvJW6o_dbHH4fmQXKOnzhQzZQ',
    appId: '1:620058340943:android:1860740d0f82ebbaa1843a',
    messagingSenderId: '620058340943',
    projectId: 'weather-1650a',
    storageBucket: 'weather-1650a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHoa0ZjOyljPFzGrtATDCR6Gy0Kis6zKs',
    appId: '1:620058340943:ios:52379c4428b89c58a1843a',
    messagingSenderId: '620058340943',
    projectId: 'weather-1650a',
    storageBucket: 'weather-1650a.firebasestorage.app',
    iosBundleId: 'com.example.weatherFlowFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHoa0ZjOyljPFzGrtATDCR6Gy0Kis6zKs',
    appId: '1:620058340943:ios:52379c4428b89c58a1843a',
    messagingSenderId: '620058340943',
    projectId: 'weather-1650a',
    storageBucket: 'weather-1650a.firebasestorage.app',
    iosBundleId: 'com.example.weatherFlowFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Rf1ZosVHly_yMdkZpSdrCr6gx4S5pGw',
    appId: '1:620058340943:web:d32a62663136611ca1843a',
    messagingSenderId: '620058340943',
    projectId: 'weather-1650a',
    authDomain: 'weather-1650a.firebaseapp.com',
    storageBucket: 'weather-1650a.firebasestorage.app',
    measurementId: 'G-FSD5292543',
  );
}
